import { test } from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { SAMPLE_PRICES, STATES_AND_UTS, indiaSeed, validPin, checkoutTotals, validateIndiaCheckout, canChangeOrderStatus, paise } from "../files/src/utils/india.js";
import { money, deliveryDate, orderNumber } from "../files/src/utils/format.js";
import { assertIndiaDatabase, assertHostingPolicy } from "../files/server/indiaGuard.js";

const valid = { name: "Demo User", email: "demo@example.com", address: "12 Sample Road", city: "Shegaon", state: "Maharashtra", zip: "444203", paymentMethod: "demo" };

test("INR formatter uses Indian grouping", () => assert.equal(money(123456.5), "₹1,23,456.50"));
test("an explicit legacy currency is not relabelled as INR", () => assert.match(money(25, "USD"), /USD/));
test("invalid display amount produces a placeholder", () => assert.equal(money(NaN), "—"));
test("PIN validator accepts a six digit PIN", () => assert.equal(validPin("444203"), true));
test("PIN validator rejects five digits", () => assert.equal(validPin("44420"), false));
test("PIN validator rejects leading zero", () => assert.equal(validPin("044203"), false));
test("PIN validator rejects mixed letters", () => assert.equal(validPin("44A203"), false));
test("PIN validator trims outside spaces only", () => { assert.equal(validPin(" 444203 "), true); assert.equal(validPin("444 203"), false); });
test("state choices have no duplicates", () => { assert.equal(STATES_AND_UTS.length, 36); assert.equal(new Set(STATES_AND_UTS).size, 36); });
test("valid Indian demo checkout passes", () => assert.deepEqual(validateIndiaCheckout(valid), {}));
test("missing checkout input returns errors without throwing", () => assert.equal(Object.keys(validateIndiaCheckout(null)).length, 7));
test("foreign or unrecognised state is rejected", () => assert.ok(validateIndiaCheckout({ ...valid, state: "California" }).state));
test("real payment mode is rejected", () => assert.ok(validateIndiaCheckout({ ...valid, paymentMethod: "card" }).paymentMethod));
test("card details are rejected even when mode says demo", () => assert.ok(validateIndiaCheckout({ ...valid, card: "4242424242424242" }).paymentMethod));
test("security code is never accepted", () => assert.ok(validateIndiaCheckout({ ...valid, cvv: "123" }).paymentMethod));
test("overlong address is rejected", () => assert.ok(validateIndiaCheckout({ ...valid, address: "a".repeat(241) }).address));
test("bad email is rejected", () => assert.ok(validateIndiaCheckout({ ...valid, email: "x@" }).email));
test("subtotals are calculated in paise", () => assert.deepEqual(checkoutTotals([{ price: 0.1, qty: 1 }, { price: 0.2, qty: 1 }]), { subtotal: 0.3, tax: 0, shipping: 0, total: 0.3, currency: "INR" }));
test("demo total has no arbitrary extra eight percent", () => assert.equal(checkoutTotals([{ price: 999, qty: 2 }]).total, 1998));
test("fractional quantities are rejected", () => assert.throws(() => checkoutTotals([{ price: 1, qty: 1.5 }])));
test("quantity above maximum is rejected", () => assert.throws(() => checkoutTotals([{ price: 1, qty: 11 }])));
test("negative money is rejected", () => assert.throws(() => paise(-1)));
test("nonfinite money is rejected", () => assert.throws(() => paise(Infinity)));
test("all twenty catalogue items have explicit sample rupee prices", () => assert.equal(Object.keys(SAMPLE_PRICES).length, 20));
test("sample prices are positive and discounts are consistent", () => { for (const [sale, before] of Object.values(SAMPLE_PRICES)) { assert.ok(sale > 0); assert.ok(before >= sale); } });
test("localisation does not mutate original catalogue input", () => { const p = { id: 1, price: 89, was: 139, reviews: 100, title: "Drill" }; const output = indiaSeed([p]); assert.equal(p.price, 89); assert.equal(output[0].price, 6499); assert.equal(output[0].reviews, 0); });
test("unmapped products are not silently relabelled", () => assert.throws(() => indiaSeed([{ id: 999 }])));
test("inaccurate dollar value is removed from the gift bundle title", () => assert.ok(!indiaSeed([{ id: 15, title: "$60" }])[0].title.includes("$")));
test("new database is explicitly marked INR", () => { const db = new DatabaseSync(":memory:"); assertIndiaDatabase(db); assert.equal(db.prepare("SELECT value FROM nimbus_store_meta WHERE key='currency'").get().value, "INR"); db.close(); });
test("already marked INR database can reopen", () => { const db = new DatabaseSync(":memory:"); assertIndiaDatabase(db); assert.doesNotThrow(() => assertIndiaDatabase(db)); db.close(); });
test("legacy database is blocked and historical value stays unchanged", () => { const db = new DatabaseSync(":memory:"); db.exec("CREATE TABLE orders (id INTEGER, total REAL); INSERT INTO orders VALUES (1, 108.00)"); assert.throws(() => assertIndiaDatabase(db), /Legacy/); assert.equal(db.prepare("SELECT total FROM orders").get().total, 108); assert.equal(db.prepare("SELECT count(*) n FROM sqlite_master WHERE name='nimbus_store_meta'").get().n, 0); db.close(); });
test("empty legacy schema is not repurposed silently", () => { const db = new DatabaseSync(":memory:"); db.exec("CREATE TABLE products (id INTEGER)"); assert.throws(() => assertIndiaDatabase(db)); db.close(); });
test("USD marker is rejected without rewriting it", () => { const db = new DatabaseSync(":memory:"); db.exec("CREATE TABLE nimbus_store_meta (key TEXT PRIMARY KEY, value TEXT); INSERT INTO nimbus_store_meta VALUES ('currency','USD')"); assert.throws(() => assertIndiaDatabase(db)); assert.equal(db.prepare("SELECT value FROM nimbus_store_meta").get().value, "USD"); db.close(); });
test("local development does not require cloud services", () => assert.doesNotThrow(() => assertHostingPolicy({ NODE_ENV: "development" })));
test("Render deployment cannot silently assume persistent storage", () => assert.throws(() => assertHostingPolicy({ RENDER: "true", NODE_ENV: "production" }), /ephemeral/));
test("ephemeral demo requires explicit opt-in", () => assert.doesNotThrow(() => assertHostingPolicy({ RENDER: "true", NODE_ENV: "production", ALLOW_EPHEMERAL_DEMO: "true" })));
test("confirmed order may ship or cancel", () => { assert.equal(canChangeOrderStatus("confirmed", "shipped"), true); assert.equal(canChangeOrderStatus("confirmed", "cancelled"), true); });
test("delivered orders cannot be rolled backwards or cancelled", () => { assert.equal(canChangeOrderStatus("delivered", "confirmed"), false); assert.equal(canChangeOrderStatus("delivered", "cancelled"), false); });
test("cancelled order cannot reopen", () => assert.equal(canChangeOrderStatus("cancelled", "shipped"), false));
test("same valid status is an idempotent status update", () => assert.equal(canChangeOrderStatus("delivered", "delivered"), true));
test("unknown status is invalid", () => assert.equal(canChangeOrderStatus("missing", "missing"), false));
test("order identifiers use UUIDs", () => assert.match(orderNumber(), /^NM-[a-f0-9-]{36}$/));
test("sample date is based on the Indian calendar day", () => assert.equal(deliveryDate(new Date("2026-09-11T20:00:00Z")), "Tuesday, 15 September"));
